# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/lunzi/Projects/Python/Kylin_Dealer/ui/order.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderWindow(object):
    def setupUi(self, OrderWindow):
        OrderWindow.setObjectName("OrderWindow")
        OrderWindow.resize(998, 488)
        self.centralwidget = QtWidgets.QWidget(OrderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.orderListTable = QtWidgets.QTableWidget(self.centralwidget)
        self.orderListTable.setGeometry(QtCore.QRect(10, 70, 521, 411))
        self.orderListTable.setObjectName("orderListTable")
        self.orderListTable.setColumnCount(5)
        self.orderListTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.orderListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderListTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderListTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderListTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderListTable.setHorizontalHeaderItem(4, item)
        self.saleItemListTable = QtWidgets.QTableWidget(self.centralwidget)
        self.saleItemListTable.setGeometry(QtCore.QRect(540, 70, 451, 411))
        self.saleItemListTable.setObjectName("saleItemListTable")
        self.saleItemListTable.setColumnCount(6)
        self.saleItemListTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.saleItemListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.saleItemListTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.saleItemListTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.saleItemListTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.saleItemListTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.saleItemListTable.setHorizontalHeaderItem(5, item)
        self.pageSizeEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pageSizeEdit.setGeometry(QtCore.QRect(160, 35, 113, 21))
        self.pageSizeEdit.setObjectName("pageSizeEdit")
        self.eachPageLabel = QtWidgets.QLabel(self.centralwidget)
        self.eachPageLabel.setGeometry(QtCore.QRect(90, 35, 60, 21))
        self.eachPageLabel.setObjectName("eachPageLabel")
        self.lastPageBtn = QtWidgets.QPushButton(self.centralwidget)
        self.lastPageBtn.setGeometry(QtCore.QRect(10, 5, 71, 61))
        self.lastPageBtn.setObjectName("lastPageBtn")
        self.nextPageBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextPageBtn.setGeometry(QtCore.QRect(280, 5, 71, 61))
        self.nextPageBtn.setObjectName("nextPageBtn")
        self.noPageLabel = QtWidgets.QLabel(self.centralwidget)
        self.noPageLabel.setGeometry(QtCore.QRect(90, 11, 60, 20))
        self.noPageLabel.setObjectName("noPageLabel")
        self.pageLabel = QtWidgets.QLabel(self.centralwidget)
        self.pageLabel.setGeometry(QtCore.QRect(160, 10, 60, 21))
        self.pageLabel.setObjectName("pageLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 20, 71, 31))
        self.label.setObjectName("label")
        self.sortComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.sortComboBox.setGeometry(QtCore.QRect(420, 20, 104, 31))
        self.sortComboBox.setObjectName("sortComboBox")
        self.sortComboBox.addItem("")
        self.sortComboBox.addItem("")
        self.sortComboBox.addItem("")
        self.sortComboBox.addItem("")
        OrderWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OrderWindow)
        QtCore.QMetaObject.connectSlotsByName(OrderWindow)

    def retranslateUi(self, OrderWindow):
        _translate = QtCore.QCoreApplication.translate
        OrderWindow.setWindowTitle(_translate("OrderWindow", "订单管理"))
        item = self.orderListTable.horizontalHeaderItem(0)
        item.setText(_translate("OrderWindow", "客户名称"))
        item = self.orderListTable.horizontalHeaderItem(1)
        item.setText(_translate("OrderWindow", "总金额"))
        item = self.orderListTable.horizontalHeaderItem(2)
        item.setText(_translate("OrderWindow", "已付"))
        item = self.orderListTable.horizontalHeaderItem(3)
        item.setText(_translate("OrderWindow", "欠款"))
        item = self.orderListTable.horizontalHeaderItem(4)
        item.setText(_translate("OrderWindow", "订单日期"))
        item = self.saleItemListTable.horizontalHeaderItem(0)
        item.setText(_translate("OrderWindow", "货物种类"))
        item = self.saleItemListTable.horizontalHeaderItem(1)
        item.setText(_translate("OrderWindow", "数量"))
        item = self.saleItemListTable.horizontalHeaderItem(2)
        item.setText(_translate("OrderWindow", "单位"))
        item = self.saleItemListTable.horizontalHeaderItem(3)
        item.setText(_translate("OrderWindow", "单价"))
        item = self.saleItemListTable.horizontalHeaderItem(4)
        item.setText(_translate("OrderWindow", "保质期"))
        item = self.saleItemListTable.horizontalHeaderItem(5)
        item.setText(_translate("OrderWindow", "生产日期"))
        self.pageSizeEdit.setText(_translate("OrderWindow", "20"))
        self.eachPageLabel.setText(_translate("OrderWindow", "每页显示："))
        self.lastPageBtn.setText(_translate("OrderWindow", "上一页"))
        self.nextPageBtn.setText(_translate("OrderWindow", "下一页"))
        self.noPageLabel.setText(_translate("OrderWindow", "当前页数："))
        self.pageLabel.setText(_translate("OrderWindow", "1"))
        self.label.setText(_translate("OrderWindow", "排序方式："))
        self.sortComboBox.setItemText(0, _translate("OrderWindow", "订单日期"))
        self.sortComboBox.setItemText(1, _translate("OrderWindow", "欠款"))
        self.sortComboBox.setItemText(2, _translate("OrderWindow", "总金额"))
        self.sortComboBox.setItemText(3, _translate("OrderWindow", "客户名称"))


