# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/lunzi/Projects/Python/Kylin_Dealer/ui/order.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderWindow(object):
    def setupUi(self, OrderWindow):
        OrderWindow.setObjectName("OrderWindow")
        OrderWindow.resize(998, 488)
        self.centralwidget = QtWidgets.QWidget(OrderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.orderListTable = QtWidgets.QTableWidget(self.centralwidget)
        self.orderListTable.setGeometry(QtCore.QRect(10, 70, 521, 411))
        self.orderListTable.setObjectName("orderListTable")
        self.orderListTable.setColumnCount(5)
        self.orderListTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.orderListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderListTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderListTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderListTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderListTable.setHorizontalHeaderItem(4, item)
        self.saleItemListTable = QtWidgets.QTableWidget(self.centralwidget)
        self.saleItemListTable.setGeometry(QtCore.QRect(540, 70, 451, 411))
        self.saleItemListTable.setObjectName("saleItemListTable")
        self.saleItemListTable.setColumnCount(6)
        self.saleItemListTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.saleItemListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.saleItemListTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.saleItemListTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.saleItemListTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.saleItemListTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.saleItemListTable.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 20, 71, 31))
        self.label.setObjectName("label")
        self.sortComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.sortComboBox.setGeometry(QtCore.QRect(420, 20, 104, 31))
        self.sortComboBox.setObjectName("sortComboBox")
        self.sortComboBox.addItem("")
        self.sortComboBox.addItem("")
        self.sortComboBox.addItem("")
        self.sortComboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(820, 20, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(820, 40, 60, 16))
        self.label_3.setObjectName("label_3")
        self.totalMoneyLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalMoneyLabel.setGeometry(QtCore.QRect(890, 20, 91, 16))
        self.totalMoneyLabel.setText("")
        self.totalMoneyLabel.setObjectName("totalMoneyLabel")
        self.totalOweLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalOweLabel.setGeometry(QtCore.QRect(890, 40, 91, 16))
        self.totalOweLabel.setText("")
        self.totalOweLabel.setObjectName("totalOweLabel")
        self.editBtn = QtWidgets.QPushButton(self.centralwidget)
        self.editBtn.setGeometry(QtCore.QRect(10, 10, 91, 51))
        self.editBtn.setObjectName("editBtn")
        self.searchEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchEdit.setGeometry(QtCore.QRect(120, 20, 231, 31))
        self.searchEdit.setObjectName("searchEdit")
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(290, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.searchBtn.setFont(font)
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchBtn.setObjectName("searchBtn")
        OrderWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OrderWindow)
        QtCore.QMetaObject.connectSlotsByName(OrderWindow)

    def retranslateUi(self, OrderWindow):
        _translate = QtCore.QCoreApplication.translate
        OrderWindow.setWindowTitle(_translate("OrderWindow", "订单管理"))
        item = self.orderListTable.horizontalHeaderItem(0)
        item.setText(_translate("OrderWindow", "客户名称"))
        item = self.orderListTable.horizontalHeaderItem(1)
        item.setText(_translate("OrderWindow", "总金额"))
        item = self.orderListTable.horizontalHeaderItem(2)
        item.setText(_translate("OrderWindow", "已付"))
        item = self.orderListTable.horizontalHeaderItem(3)
        item.setText(_translate("OrderWindow", "欠款"))
        item = self.orderListTable.horizontalHeaderItem(4)
        item.setText(_translate("OrderWindow", "订单日期"))
        item = self.saleItemListTable.horizontalHeaderItem(0)
        item.setText(_translate("OrderWindow", "货物种类"))
        item = self.saleItemListTable.horizontalHeaderItem(1)
        item.setText(_translate("OrderWindow", "数量"))
        item = self.saleItemListTable.horizontalHeaderItem(2)
        item.setText(_translate("OrderWindow", "单位"))
        item = self.saleItemListTable.horizontalHeaderItem(3)
        item.setText(_translate("OrderWindow", "单价"))
        item = self.saleItemListTable.horizontalHeaderItem(4)
        item.setText(_translate("OrderWindow", "保质期"))
        item = self.saleItemListTable.horizontalHeaderItem(5)
        item.setText(_translate("OrderWindow", "生产日期"))
        self.label.setText(_translate("OrderWindow", "排序方式："))
        self.sortComboBox.setItemText(0, _translate("OrderWindow", "订单日期"))
        self.sortComboBox.setItemText(1, _translate("OrderWindow", "欠款"))
        self.sortComboBox.setItemText(2, _translate("OrderWindow", "总金额"))
        self.sortComboBox.setItemText(3, _translate("OrderWindow", "客户名称"))
        self.label_2.setText(_translate("OrderWindow", "总交易额："))
        self.label_3.setText(_translate("OrderWindow", "总欠款："))
        self.editBtn.setText(_translate("OrderWindow", "修改订单"))
        self.searchBtn.setText(_translate("OrderWindow", "搜索"))


