# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/lunzi/Projects/Python/Kylin_Dealer/ui/stock.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StockWindow(object):
    def setupUi(self, StockWindow):
        StockWindow.setObjectName("StockWindow")
        StockWindow.resize(1092, 490)
        self.cargoTypeListTable = QtWidgets.QTableWidget(StockWindow)
        self.cargoTypeListTable.setGeometry(QtCore.QRect(10, 80, 521, 401))
        self.cargoTypeListTable.setObjectName("cargoTypeListTable")
        self.cargoTypeListTable.setColumnCount(5)
        self.cargoTypeListTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.cargoTypeListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cargoTypeListTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cargoTypeListTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cargoTypeListTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cargoTypeListTable.setHorizontalHeaderItem(4, item)
        self.cargoListTable = QtWidgets.QTableWidget(StockWindow)
        self.cargoListTable.setGeometry(QtCore.QRect(540, 80, 541, 401))
        self.cargoListTable.setObjectName("cargoListTable")
        self.cargoListTable.setColumnCount(3)
        self.cargoListTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.cargoListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cargoListTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cargoListTable.setHorizontalHeaderItem(2, item)
        self.buyBtn = QtWidgets.QPushButton(StockWindow)
        self.buyBtn.setGeometry(QtCore.QRect(540, 10, 111, 61))
        self.buyBtn.setObjectName("buyBtn")
        self.editBtn = QtWidgets.QPushButton(StockWindow)
        self.editBtn.setGeometry(QtCore.QRect(970, 10, 111, 61))
        self.editBtn.setObjectName("editBtn")
        self.lastPageBtn = QtWidgets.QPushButton(StockWindow)
        self.lastPageBtn.setGeometry(QtCore.QRect(190, 10, 71, 61))
        self.lastPageBtn.setObjectName("lastPageBtn")
        self.pageSizeEdit = QtWidgets.QLineEdit(StockWindow)
        self.pageSizeEdit.setGeometry(QtCore.QRect(340, 40, 113, 21))
        self.pageSizeEdit.setObjectName("pageSizeEdit")
        self.eachPageLabel = QtWidgets.QLabel(StockWindow)
        self.eachPageLabel.setGeometry(QtCore.QRect(270, 40, 60, 21))
        self.eachPageLabel.setObjectName("eachPageLabel")
        self.noPageLabel = QtWidgets.QLabel(StockWindow)
        self.noPageLabel.setGeometry(QtCore.QRect(270, 16, 60, 20))
        self.noPageLabel.setObjectName("noPageLabel")
        self.pageLabel = QtWidgets.QLabel(StockWindow)
        self.pageLabel.setGeometry(QtCore.QRect(340, 15, 60, 21))
        self.pageLabel.setObjectName("pageLabel")
        self.nextPageBtn = QtWidgets.QPushButton(StockWindow)
        self.nextPageBtn.setGeometry(QtCore.QRect(460, 10, 71, 61))
        self.nextPageBtn.setObjectName("nextPageBtn")
        self.addCargoTypeBtn = QtWidgets.QPushButton(StockWindow)
        self.addCargoTypeBtn.setGeometry(QtCore.QRect(10, 10, 91, 61))
        self.addCargoTypeBtn.setObjectName("addCargoTypeBtn")
        self.delCargoTypeBtn = QtWidgets.QPushButton(StockWindow)
        self.delCargoTypeBtn.setGeometry(QtCore.QRect(100, 10, 71, 61))
        self.delCargoTypeBtn.setObjectName("delCargoTypeBtn")
        self.saleBtn = QtWidgets.QPushButton(StockWindow)
        self.saleBtn.setGeometry(QtCore.QRect(650, 10, 111, 61))
        self.saleBtn.setObjectName("saleBtn")

        self.retranslateUi(StockWindow)
        QtCore.QMetaObject.connectSlotsByName(StockWindow)

    def retranslateUi(self, StockWindow):
        _translate = QtCore.QCoreApplication.translate
        StockWindow.setWindowTitle(_translate("StockWindow", "库存管理"))
        item = self.cargoTypeListTable.horizontalHeaderItem(0)
        item.setText(_translate("StockWindow", "货物种类"))
        item = self.cargoTypeListTable.horizontalHeaderItem(1)
        item.setText(_translate("StockWindow", "单位"))
        item = self.cargoTypeListTable.horizontalHeaderItem(2)
        item.setText(_translate("StockWindow", "数量"))
        item = self.cargoTypeListTable.horizontalHeaderItem(3)
        item.setText(_translate("StockWindow", "保质期"))
        item = self.cargoTypeListTable.horizontalHeaderItem(4)
        item.setText(_translate("StockWindow", "售价"))
        item = self.cargoListTable.horizontalHeaderItem(0)
        item.setText(_translate("StockWindow", "生产日期"))
        item = self.cargoListTable.horizontalHeaderItem(1)
        item.setText(_translate("StockWindow", "数量"))
        item = self.cargoListTable.horizontalHeaderItem(2)
        item.setText(_translate("StockWindow", "备注"))
        self.buyBtn.setText(_translate("StockWindow", "进货"))
        self.editBtn.setText(_translate("StockWindow", "修改"))
        self.lastPageBtn.setText(_translate("StockWindow", "上一页"))
        self.pageSizeEdit.setText(_translate("StockWindow", "15"))
        self.eachPageLabel.setText(_translate("StockWindow", "每页显示："))
        self.noPageLabel.setText(_translate("StockWindow", "当前页数："))
        self.pageLabel.setText(_translate("StockWindow", "1"))
        self.nextPageBtn.setText(_translate("StockWindow", "下一页"))
        self.addCargoTypeBtn.setText(_translate("StockWindow", "添加"))
        self.delCargoTypeBtn.setText(_translate("StockWindow", "删除"))
        self.saleBtn.setText(_translate("StockWindow", "出货"))


